### ISSUE TITLE
숭실대 학생이 사용할수  있는 오픈 API Gateway

### ISSUE THREAD

**Issue by siyul-park** [Soongsil-Developers/ssu-devcamp#3]
# [SSU-APIGW] 숭실대 학생이 사용할 수 있는 오픈 API Gateway
## 필요 분야 및 인원
Backend, Web FE - 3명 or 4명

## 필요 스택
Backend : Spring, Flask, Django 와 같은 웹 프레임워크, DB, (non-blocking 기반 프레임워크 권장)
Web FE : HTML5, CSS, JS, TS, React, Vue 등 통상적인 Web FE 도구

## 프로젝트 설명
숭실대 학생이 사용할 수 있는 오픈 API Gateway입니다.

https://github.com/Soongsil-Developers/ssu-devcamp/issues/1 와 연동해서 숭실대 학생 인증이나 사용량 관리, 그리고 필요에 따라 과금을 제공하여 숭실대 학생들을 위한 서비스를 더 쉽게 개발을 할 수 있게 도와줍니다.

새부적인 기획은 정해지지 않았으며 같이 진행 예정입니다.

### 레퍼런스
https://github.com/Kong/kong

### 프로젝트 멘토
- 추후 공개

**Comment by Dev-Beom** [comment]
시율님 저 관심있습니다
